apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-nodeport
    demo: service
spec:   # list of container
  containers:
  - name: nginx-nodeport
    image: nginx # open just information
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx-nodeport
    demo: service
  ports:
    - protocol: TCP
      port: 80    # service-port
      targetPort: 80   # container-port
