apiVersion: v1
kind: PersistentVolume
metadata:
  name: eds-static
spec:
  accessModes:
  - ReadWriteOnce # EBS volume read and write onces
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0ae9b7a67ebb3a3c7 # you create manuval volume id
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---   
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeselector:
    zone: 1f    
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static 
---    
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer  # Corrected capitalization
  selector:
    demo: ebs-static
  ports:
    - protocol: TCP
      port: 80    # service-port
      targetPort: 80   # container-port
