apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: fs-0ace0e3b18aeee267 # elasti file system create manuval
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: efs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi    
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b # your zone location
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port