apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop
spec:   # list of container
  containers:
  - name: hello-pod
    image: nginx # open just information
    ports:
    - containerPort: 80
