apiVersion: v1
kind: pod
metadata:
  name: multi-container
spec:  
  containers:
   - name: nginx
     image: nginx
     ports:
       - containerPort:80
   - name: almalinux
     image: almalinux:8
     command: ["slepp", "300"]