apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    name: rajesh
    surname: veeranki
  annotations:
    location: "bommuluru"
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
        - containerPort: 80
