apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    name: rajesh
    surname: veeranki
spec:
  containers:
    - name: env-demo-container
      image: nginx
      env:
      - name: demo_greeting
        value: "hello from env"
      - name: demo_farewell
        value: "such a sweet mango" 
      ports:
        - containerPort: 80
