apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-pod
    image: neginx  # line just information
    ports:
    - containers: 80
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
        
  
  
  
  
  
  
  
  
  