apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: Cource
      valueFrom:
        configMapKeyRef:
          name: devops-configmap
          key: Cource
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-configmap
          key: trainer
