apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: Cource
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: Cource
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1
spec:
  containers:
  - name: config-pod-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: devops-config
